name: CI-utile


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: codecov/codecov-action@v1
    # Introduction
    - name: utile building
      run: pip install -r requirements.txt

    # Runs test
    - name: Running tests
      run: |
        echo Building...
        python -m unittest discover tests
